/* Checkpoints 014–017: target-specific recovery and additional body shapes. */
(() => {
  'use strict';
  const shapeSources=['SHAPE_RECOVERY_THEOREMS.md','shape_recovery_validation.json'];
  const entries=[
    {
      id:'cap-study',short:'Noise and the range cap',title:'A small change can admit a distant family.',dimension:2,status:'Certified global bounds',
      question:'Compare noise levels and caps on the same planar triangle.',
      assumptions:['Unit rigid right triangle; two shared anchors near (−1,0) and (1,0).','Three distance ratios lie within 1 ± ε; a fifth range is no larger than the reference.','The physical reference range r has the selected upper cap. Reflections are included.'],
      finding:'With δ = .05 and ε = 1%, raising the cap from 2 to 10 raises optimal range error from about .0531 to 4.4672. At ε = .5%, cap 10 excludes the distant family.',
      scope:'The horizontal axis is the value of r, not a map of positions. Colored spans are outer windows; the drawing does not assert that every interior range is attainable.',
      evidence:'Six complete cover certificates and 28 physical witnesses support 18 cap/error cases. All were rechecked in checkpoint 015.',
      sources:['NOISY_CAP_TRIANGLE_THEOREMS.md','NOISY_CAP_REPORT.md','noisy_triangle_results.json','noisy_triangle_validation.json'],terms:['minimax','shared','certificate','target'],
      controls:[{key:'epsilon',label:'Ratio tolerance',type:'select',value:'0.01',options:[['0.005','0.5%'],['0.01','1%'],['0.02','2%']]},{key:'delta',label:'Original anchor uncertainty',type:'select',value:'0.05',options:[['0','Exact anchors'],['0.05','Disks of radius 0.05']]},{key:'cap',label:'Reference range cap',type:'select',value:'10',options:[['2','2 units'],['10','10 units'],['12','12 units']]}],
      guide:{character:'Global ambiguity · a cap excludes whole families',plain:'A nearby solution can look well determined while a distant explanation also fits. A physical range cap can exclude that distant family. Small noise changes can decide whether it is admitted.',use:'Comparing a real operating-range restriction with better ratio precision. This is a geometric benchmark, not a calibrated device.',intro:'Start at cap 2, then allow 10. Finally halve the ratio tolerance.',examples:[{label:'Cap 2',values:{cap:'2',epsilon:'0.01',delta:'0.05'},expect:'Only the near outer window remains. Error is about 0.0531.'},{label:'Allow range 10',values:{cap:'10',epsilon:'0.01',delta:'0.05'},expect:'The distant family now fits. Error rises to about 4.4672.'},{label:'Halve the noise',values:{cap:'10',epsilon:'0.005',delta:'0.05'},expect:'The distant onset moves beyond 11.24, so cap 10 excludes it.'}]}
    },
    {
      id:'measurement',short:'Where to put another beacon',title:'A perfect extra reading can still leave two answers.',dimension:2,status:'Certified comparison + exact pair',
      question:'Move the extra beacon from (0,1) to (0,2), keeping the target and original data fixed.',
      assumptions:['The checkpoint-014 triangle has ε = 1%, δ = .05 and reference cap 10.','A third beacon measures absolute distance to X0. It is fixed and exact.','The guarantee covers all possible future readings and O(2) poses, including reflections.'],
      finding:'At (0,1), an exact common reading leaves optimal reference-range error about 1.027867. At (0,2), even ±.01 reading noise gives error about .109445.',
      scope:'Both colored triangles are physical witnesses. Moving the beacon loads a different certified pair. It is not the same pair following a continuous motion. Close view can crop the anchors.',
      evidence:'Complete rational interval trees certify the (0,2) upper bounds; rational physical pairs give matching lower bounds. The (0,1) reading equality is exact algebra, not numerical proximity.',
      sources:['THIRD_BEACON_THEOREM.md','third_beacon_validation.json','third_beacon_physical_pairs.json','third_beacon_placement_counterexample.json'],terms:['target','minimax','shared','certificate'],
      controls:[{key:'height',label:'Extra beacon position',type:'select',value:'1',options:[['1','(0,1) · exact common reading'],['2','(0,2) · ±0.01 noise']]},{key:'wide',label:'Include the anchors in the view',type:'check',value:true}],
      guide:{character:'Measurement design · distinguish the competing explanations',plain:'The new beacon measures its own distance to the tag. That need not tell us the distance to the original beacon. At the first placement, a nearer tag on one side and a farther tag on the other give precisely the same new reading.',use:'Testing whether a proposed extra measurement resolves the actual ambiguity, before paying for it. These two positions are examples, not a global placement optimum.',intro:'Compare the two possible triangles, then change the measurement location.',examples:[{label:'Same perfect reading',values:{height:'1',wide:true},expect:'Reference ranges near 7.9443 and 10 give the same new reading near 8.9266.'},{label:'Better placement',values:{height:'2',wide:true},expect:'The largest surviving target separation is about 0.218889, giving error about 0.109445.'},{label:'Inspect the closer pair',values:{height:'2',wide:false},expect:'Zoom into the two near-optimal witness poses. Their new reading intervals overlap.'}]}
    },
    {
      id:'body-sphere',short:'A fully observed round body',title:'A full spherical boundary has an exact range formula.',dimension:3,status:'Exact continuous-family theorem',
      question:'Compare the near and distant solutions for an ideal sphere of known radius 1.',
      assumptions:['One actual shared anchor observes every point on a known unit spherical boundary.','Every distance ratio to a marked reference point lies in [1−ε,1+ε].','This is complete boundary coverage in at least two dimensions, not a few sampled points.'],
      finding:'Reference ranges fill [2/(2+ε), 2/(2−ε)] and [1/ε, ∞). At ε = 1%, the far family starts at 100.',
      scope:'The mesh represents the full body boundary; the other point is its one ranging anchor. This reverses the roles in the older sphere-of-anchors exhibit. Far-view scale changes to fit the chosen example.',
      evidence:'The near and far branches follow by eliminating the anchor’s distance from the sphere center. 10,800 rational instances audit the formula.',sources:shapeSources,terms:['target','escape','prior','shared'],
      controls:[{key:'epsilon',label:'Ratio tolerance ε',type:'range',min:.01,max:.3,step:.01,value:.1},{key:'branch',label:'Displayed physical family',type:'select',value:'near',options:[['near','Near anchor · near upper endpoint'],['far','Distant anchor · first far range']]}],
      guide:{character:'Shape and coverage · an ideal exact benchmark',plain:'Knowing a round body and measuring all around it is strong information. Yet relative errors still allow sufficiently distant anchors, where all those distances look nearly equal.',use:'A reference problem for studying what incomplete surface coverage loses. It is not a guarantee for a handful of points on a sphere.',intro:'The unit sphere stays the same. Switch from an anchor near its center to the first distant example.',examples:[{label:'Near family at 10%',values:{epsilon:.1,branch:'near'},expect:'The near reference interval is about [0.9524, 1.0526].'},{label:'Distant family at 10%',values:{epsilon:.1,branch:'far'},expect:'The first distant reference range is 10.'},{label:'Distant family at 1%',values:{epsilon:.01,branch:'far'},expect:'The first distant range moves to 100. It still exists without a cap.'}]}
    },
    {
      id:'body-block',short:'Shapes sharing equal ranges',title:'The dimensions tell us when all ranges can agree.',dimension:3,status:'Exact block characterization',
      question:'Rotate a rectangle or triangle around two anchors, then try a full 3D tetrahedron.',
      assumptions:['Every body vertex must have the same range to every anchor.','The body is rigid and the actual anchors are distinct.','This complete equal-distance graph differs from the partially observed triangle in 014.'],
      finding:'A planar cyclic body and two anchors can fit in 3D when their spans are perpendicular. A full-dimensional tetrahedron cannot be equidistant from two distinct anchors.',
      scope:'For the rectangle and triangle the angle moves the physical body while the anchors stay fixed. The tetrahedron drawing illustrates disagreement; the dimension theorem proves impossibility for every placement.',
      evidence:'Distance subtraction proves perpendicular affine spans, relative circumcenters, and r² = R_body² + R_anchors² + residual-offset².',sources:shapeSources,terms:['pose','prior','revolution','shared'],
      controls:[{key:'shape',label:'Known body',type:'select',value:'rectangle',options:[['rectangle','Rectangle · sides 2 and 1'],['triangle','Equilateral triangle · edge 1'],['tetra','Regular tetrahedron · edge 1']]},{key:'separation',label:'Anchor separation D',type:'range',min:.5,max:4,step:.1,value:2},{key:'angle',label:'Physical rotation about x axis',type:'range',min:0,max:360,step:1,value:30}],
      guide:{character:'Dimension · where the remaining freedom lives',plain:'A flat cyclic body can sit around an anchor axis, with all its vertices equally far from each anchor. A tetrahedron already occupies three independent dimensions, leaving no direction for a second distinct equal-range anchor.',use:'Checking whether an assumed equal-reading pattern is even physically compatible with the sensor arrangement and body.',intro:'Turn the rectangle around its axis; its common range does not change. Then select the tetrahedron.',examples:[{label:'Rectangle',values:{shape:'rectangle',separation:2,angle:30},expect:'All eight ranges equal 1.5. Its pose still turns around the anchor line.'},{label:'Turn it',values:{shape:'rectangle',separation:2,angle:160},expect:'The body has moved; the common range remains 1.5.'},{label:'Try a tetrahedron',values:{shape:'tetra',separation:2,angle:30},expect:'Two distinct equal-range anchors are impossible for a full-dimensional tetrahedron.'}]}
    },
    {
      id:'flexible',short:'A rhombus is not a square',title:'Four known sides can hide a nearly collapsed shape.',dimension:2,status:'Exact rational witness',
      question:'Compare a unit square with a unit-sided rhombus under the same reported ratio tolerance.',
      assumptions:['All four sides have length 1; the shape may be a convex rhombus.','One fixed anchor observes all four vertices with ratio tolerance 1% and reference cap 10.','A rigid square prior would be additional information, not implied by the side lengths.'],
      finding:'Both a square of area 1 and a thin rhombus of area about .004 fit. The thin shape’s short diagonal is about .004, compared with √2 for the square.',
      scope:'Both complete candidates use the same anchor at the origin; each body is translated accordingly. Close view centers the selected body and may crop the anchor.',
      evidence:'Exact rational coordinates verify all four unit sides, every range ratio and the cap. Diagonal recovery near collapse has a square-root, rather than uniform linear, sensitivity.',sources:shapeSources,terms:['prior','shared','target','feasible'],
      controls:[{key:'shape',label:'Compatible body',type:'select',value:'square',options:[['square','Unit square'],['thin','Thin unit-sided rhombus']]},{key:'wide',label:'Include the ranging anchor',type:'check',value:false}],
      guide:{character:'Structural uncertainty · lengths do not settle every angle',plain:'A four-bar frame can fold while keeping every side unchanged. These range proportions are loose enough to admit a nearly folded frame as well as a square. Calling it a square would silently add an angle constraint.',use:'Checking whether a manufactured part, linkage or sensor mount is really rigid enough for the reconstruction prior being used.',intro:'Switch between two physically compatible explanations with the same four side lengths.',examples:[{label:'Square',values:{shape:'square',wide:false},expect:'Area is 1; both diagonals are √2.'},{label:'Nearly folded',values:{shape:'thin',wide:false},expect:'All four sides are still 1, but area and the short diagonal are about .004.'},{label:'Show the anchor',values:{shape:'thin',wide:true},expect:'The thin shape is about 9.0554 units from the same fixed anchor and remains below cap 10.'}]}
    },
    {
      id:'visible-arc',short:'Radius versus visible arc',title:'The radius can be unbounded while the arc is precise.',dimension:2,status:'Exact target comparison',
      question:'Keep the same allowed sagitta interval and change which geometric quantity you want.',
      assumptions:['The exact chord runs from (−1,0) to (1,0).','The shape is a minor circular arc with positive sagitta h ≤ h_max < 1.','Visible-arc error is maximum vertical error at the same horizontal coordinate.'],
      finding:'The full circle radius has no upper bound. The optimal visible-arc error is exactly h_max/2, and curvature has a finite interval.',
      scope:'Vertical magnification is labeled explicitly. The green midpoint-sagitta arc is a valid circle and is optimal for the stated visible-graph error. Nothing here recovers an unobserved continuation.',
      evidence:'The visible arc changes by at most the sagitta change, with equality at the chord midpoint. This proves the exact minimax value.',sources:shapeSources,terms:['target','minimax','prior'],
      controls:[{key:'height',label:'Maximum positive sagitta h_max',type:'range',min:.001,max:.2,step:.001,value:.01},{key:'gain',label:'Vertical display magnification',type:'select',value:'50',options:[['1','True aspect ratio'],['10','10× vertically'],['50','50× vertically']]}],
      guide:{character:'Target choice · an unstable parameter need not spoil the visible shape',plain:'Very large circles look almost straight over a short chord. We may never learn the full radius from this measurement, yet know the visible curve closely enough for the job.',use:'Separating a local surface-tolerance question from an attempt to recover the complete circle. Horizontal registration and noncircular shapes need further assumptions.',intro:'Inspect the allowed arcs and their midpoint estimate, then return to true aspect ratio.',examples:[{label:'Height at most .01',values:{height:.01,gain:'50'},expect:'The radius is unbounded above, but the visible-arc error is exactly .005.'},{label:'True aspect ratio',values:{height:.01,gain:'1'},expect:'The compatible arcs are nearly indistinguishable at their actual scale.'},{label:'Tighter visible shape',values:{height:.002,gain:'50'},expect:'The optimal visible-arc error is .001. The radius still has no upper bound.'}]}
    },
    {
      id:'flat-depth',short:'Depth near a flat shape',title:'Near a plane, depth improves only as a square root.',dimension:3,status:'Exact depth and reflection formulas',
      question:'Reduce the uncertainty of the common squared range, and test a reflected pair.',
      assumptions:['Base anchors are (0,0,0), (2,0,0), (0,2,0).','The point has exactly equal squared ranges q ∈ [2,2+ν]. Thus it is (1,1,z).','The optional beacon is (1,1,1) with additive range noise ±.01.'],
      finding:'Signed depth lies in [−√ν,√ν]. Its optimal error is √ν; unsigned-depth error is √ν/2. A fourth beacon can separate a fixed reflected pair, but positive noise cannot separate every pair approaching the plane.',
      scope:'The two points shown are the endpoint pair z = ±√ν. Their extra-reading separation is a test of that pair, not a complete new posterior certificate.',
      evidence:'Subtracting equal squared ranges gives x=y=1 and q=2+z². The new pair’s range difference is 2 min(1,|z|).',sources:shapeSources,terms:['squared','target','pose','minimax'],
      controls:[{key:'nu',label:'Common squared-range interval width ν',type:'range',min:0,max:1,step:.0001,value:.04},{key:'beacon',label:'Test the extra out-of-plane beacon',type:'check',value:false}],
      guide:{character:'Singularity · flat geometry hides depth',plain:'Moving a point a little away from a plane changes these squared distances only quadratically. A much more precise distance measurement can therefore produce a smaller-than-expected improvement in depth.',use:'Understanding nearly flat triangulation or depth reconstruction, and checking whether an extra viewpoint removes a reflection ambiguity at the required precision.',intro:'Reduce squared-range uncertainty by a factor of 100, then examine a reflected pair close to the plane.',examples:[{label:'ν = .04',values:{nu:.04,beacon:false},expect:'Signed-depth error is .2; unsigned-depth error is .1.'},{label:'100× smaller interval',values:{nu:.0004,beacon:false},expect:'Signed-depth error becomes .02: only a 10× improvement.'},{label:'Pair at the noise threshold',values:{nu:.0001,beacon:true},expect:'Depths ±.01 still share a possible ±.01 beacon reading. Closed intervals touch at equality.'}]}
    },
    {
      id:'missing-section',short:'What a perfect slice misses',title:'The same exact slice belongs to many 3D bodies.',dimension:3,status:'Exact indistinguishable family',
      question:'Change the ellipsoid’s height without changing the observed equator.',
      assumptions:['An axis-aligned ellipsoid has known horizontal semiaxes 2 and 1.','Only its complete exact section at z = 0 is observed.','Its positive vertical semiaxis c has no upper prior bound.'],
      finding:'Every c > 0 gives the same measured ellipse. Full height and volume are unbounded above, even with a perfect slice.',
      scope:'The slider displays finite members of an unbounded family. The purple body is the c = 1 reference, not an uncertainty boundary.',
      evidence:'Substituting z = 0 removes c from the ellipsoid equation. Exact rational section samples audit the identity.',sources:shapeSources,terms:['target','prior','feasible'],
      controls:[{key:'height',label:'Unobserved vertical semiaxis c',type:'range',min:.1,max:5,step:.1,value:2}],
      guide:{character:'Missing data · precision cannot restore an absent dimension',plain:'A perfectly measured middle slice tells us the ellipse in that plane. It does not tell us how tall the object is. Increasing precision on the same slice leaves that freedom untouched.',use:'Recognizing when another cross-section, viewpoint, or justified shape parameter is more valuable than refining the existing observation.',intro:'Flatten and stretch the body while watching the measured cyan ellipse.',examples:[{label:'Flat body',values:{height:.2},expect:'The vertical extent is .4. The observed ellipse is unchanged.'},{label:'Tall body',values:{height:5},expect:'The vertical extent is 10. Exactly the same slice still fits.'}]}
    },
    {
      id:'vector-error',short:'One number versus a position',title:'Half the diameter is not always the position error.',dimension:3,status:'Classical enclosing-ball geometry',
      question:'Compare the covering-ball guarantee, then use a prior to exclude one possible answer.',
      assumptions:['One observation leaves the colored vertices as possible target positions.','An estimate may be any point in the ambient Euclidean space.','The optional prior rules out one vertex. The loss is Euclidean position error.'],
      finding:'All vertices of the unit-circumradius triangle or tetrahedron are needed to keep optimal error at 1. Excluding one lets the center move and the guarantee shrink.',
      scope:'The center is the optimal position estimate. Gray marks show a candidate excluded by the selected prior. The enclosing-ball foundations are classical; 017 states their consequence for prior value.',
      evidence:'The contact points and their barycenter certify the smallest ball. A general compact-set theorem gives an exact prior threshold through at most m+1 contact states.',sources:['GENERAL_RECOVERY_FRAMEWORK.md','shape_recovery_validation.json','PRIOR_VALUE_THRESHOLD_THEOREM.md','prior_value_threshold_validation.json'],terms:['target','minimax','prior'],
      controls:[{key:'shape',label:'Possible positions',type:'select',value:'tetra',options:[['triangle','Equilateral triangle · 2D'],['tetra','Regular tetrahedron · 3D']]},{key:'exclude',label:'Prior excludes one candidate',type:'check',value:false}],
      guide:{character:'Error metric · which extreme answers must survive',plain:'For one number, keeping both extremes preserves the original error. A position can be uncertain in several directions at once. Here all the corners together hold the uncertainty ball in place. Remove one, and it can shrink.',use:'Testing which competing explanations a shape prior must eliminate to improve the actual target guarantee. This also prevents a scalar range bound from being mistaken for position accuracy.',intro:'Compare all candidates with a prior that excludes one. Watch the optimal center move.',examples:[{label:'Triangle of positions',values:{shape:'triangle',exclude:false},expect:'Half the diameter is about .8660; the actual optimal error is 1.'},{label:'Exclude a triangle corner',values:{shape:'triangle',exclude:true},expect:'The remaining two answers have optimal error √3/2, about .8660.'},{label:'Tetrahedron of positions',values:{shape:'tetra',exclude:false},expect:'Half the diameter is about .8165; the actual optimal error is 1.'},{label:'Exclude a tetrahedron corner',values:{shape:'tetra',exclude:true},expect:'Three answers remain. Their optimal error is √(8/9), about .9428; half their diameter is still too small.'}]}
    }
  ];
  for(const entry of entries){const {guide,...exhibit}=entry;exhibit.group='New recovery results · 014–017';RESEARCH_CATALOG.exhibits.push(exhibit);RESEARCH_GUIDES[exhibit.id]=guide;}
})();
